home:
   path: /
   controller: App\Controller\DefaultController::index

patient:
    path: /patient
    controller: App\Controller\PatientController::index

medecin:
    path: /medecin
    controller: App\Controller\MedecinController::index

ordonnance:
    path: /ordonnance
    controller: App\Controller\OrdonnanceController::index

consultation: 
    path: /consultation
    controller: App\Controller\ConsultationController::index

ligne_prescription:
    path: /ligne/prescription
    controller: App\Controller\LignePrescriptionController::index

medicament:
    path: /medicament
    controller: App\Controller\MedicamentCOntroller::index
    